/* Auto-generated by build_favorites_hierarchy_fs.py */
#ifndef CATALOG_FAVORITES_H
#define CATALOG_FAVORITES_H

#include "fuse_ntfs.h"

static inline void init_favorites_catalog(void) {
    pthread_rwlock_wrlock(&g_catalog_rwlock);
    g_num_files = 9;

    /* Entry 0: 01 - GLOBO RJ.ts (Inode 27, 4000000000 B) */
    memset(&g_files[0], 0, sizeof(struct virtual_file));
    g_files[0].file_id = 0;
    strncpy(g_files[0].id, "10006", sizeof(g_files[0].id) - 1);
    strncpy(g_files[0].name, "GLOBO RIO DE JANEIRO (RJ) FHD¹", sizeof(g_files[0].name) - 1);
    strncpy(g_files[0].path, "01 - GLOBO RJ.ts", sizeof(g_files[0].path) - 1);
    g_files[0].file_size = 4000000000ULL;
    g_files[0].src_type = SRC_LIVE_FIFO;
    g_files[0].state = VOD_STATE_READY;
    g_files[0].bytes_available = 4000000000ULL;
    g_files[0].num_extents = 1;
    g_files[0].extents[0].id = 0;
    g_files[0].extents[0].vcn_start = 0ULL;
    g_files[0].extents[0].vcn_end = 976562ULL;
    g_files[0].extents[0].lcn_start = 5259264ULL;
    g_files[0].extents[0].lcn_end = 6235826ULL;
    g_files[0].extents[0].file_start = 0ULL;
    g_files[0].extents[0].file_end = 4000000000ULL;
    g_files[0].extents[0].lba_start = 42074112ULL;
    g_files[0].extents[0].lba_end = 49886615ULL;
    g_files[0].extents[0].num_clusters = 976563ULL;
    g_files[0].active = 1;
    g_files[0].http_sock = -1;
    pthread_mutex_init(&g_files[0].vf_mu, NULL);
    pthread_cond_init(&g_files[0].vf_cv, NULL);

    /* Entry 1: 02 - BBC WORLD.ts (Inode 28, 4000000000 B) */
    memset(&g_files[1], 0, sizeof(struct virtual_file));
    g_files[1].file_id = 1;
    strncpy(g_files[1].id, "1765055", sizeof(g_files[1].id) - 1);
    strncpy(g_files[1].name, "BBC WORLD FHD¹", sizeof(g_files[1].name) - 1);
    strncpy(g_files[1].path, "02 - BBC WORLD.ts", sizeof(g_files[1].path) - 1);
    g_files[1].file_size = 4000000000ULL;
    g_files[1].src_type = SRC_LIVE_FIFO;
    g_files[1].state = VOD_STATE_READY;
    g_files[1].bytes_available = 4000000000ULL;
    g_files[1].num_extents = 1;
    g_files[1].extents[0].id = 0;
    g_files[1].extents[0].vcn_start = 0ULL;
    g_files[1].extents[0].vcn_end = 976562ULL;
    g_files[1].extents[0].lcn_start = 6235827ULL;
    g_files[1].extents[0].lcn_end = 7212389ULL;
    g_files[1].extents[0].file_start = 0ULL;
    g_files[1].extents[0].file_end = 4000000000ULL;
    g_files[1].extents[0].lba_start = 49886616ULL;
    g_files[1].extents[0].lba_end = 57699119ULL;
    g_files[1].extents[0].num_clusters = 976563ULL;
    g_files[1].active = 1;
    g_files[1].http_sock = -1;
    pthread_mutex_init(&g_files[1].vf_mu, NULL);
    pthread_cond_init(&g_files[1].vf_cv, NULL);

    /* Entry 2: 03 - CNN BRASIL.ts (Inode 29, 4000000000 B) */
    memset(&g_files[2], 0, sizeof(struct virtual_file));
    g_files[2].file_id = 2;
    strncpy(g_files[2].id, "206087", sizeof(g_files[2].id) - 1);
    strncpy(g_files[2].name, "CNN BRASIL FHD¹", sizeof(g_files[2].name) - 1);
    strncpy(g_files[2].path, "03 - CNN BRASIL.ts", sizeof(g_files[2].path) - 1);
    g_files[2].file_size = 4000000000ULL;
    g_files[2].src_type = SRC_LIVE_FIFO;
    g_files[2].state = VOD_STATE_READY;
    g_files[2].bytes_available = 4000000000ULL;
    g_files[2].num_extents = 1;
    g_files[2].extents[0].id = 0;
    g_files[2].extents[0].vcn_start = 0ULL;
    g_files[2].extents[0].vcn_end = 976562ULL;
    g_files[2].extents[0].lcn_start = 7212390ULL;
    g_files[2].extents[0].lcn_end = 8188952ULL;
    g_files[2].extents[0].file_start = 0ULL;
    g_files[2].extents[0].file_end = 4000000000ULL;
    g_files[2].extents[0].lba_start = 57699120ULL;
    g_files[2].extents[0].lba_end = 65511623ULL;
    g_files[2].extents[0].num_clusters = 976563ULL;
    g_files[2].active = 1;
    g_files[2].http_sock = -1;
    pthread_mutex_init(&g_files[2].vf_mu, NULL);
    pthread_cond_init(&g_files[2].vf_cv, NULL);

    /* Entry 3: 04 - BAND RJ.ts (Inode 30, 4000000000 B) */
    memset(&g_files[3], 0, sizeof(struct virtual_file));
    g_files[3].file_id = 3;
    strncpy(g_files[3].id, "207177", sizeof(g_files[3].id) - 1);
    strncpy(g_files[3].name, "BAND RJ FHD²", sizeof(g_files[3].name) - 1);
    strncpy(g_files[3].path, "04 - BAND RJ.ts", sizeof(g_files[3].path) - 1);
    g_files[3].file_size = 4000000000ULL;
    g_files[3].src_type = SRC_LIVE_FIFO;
    g_files[3].state = VOD_STATE_READY;
    g_files[3].bytes_available = 4000000000ULL;
    g_files[3].num_extents = 1;
    g_files[3].extents[0].id = 0;
    g_files[3].extents[0].vcn_start = 0ULL;
    g_files[3].extents[0].vcn_end = 976562ULL;
    g_files[3].extents[0].lcn_start = 8188953ULL;
    g_files[3].extents[0].lcn_end = 9165515ULL;
    g_files[3].extents[0].file_start = 0ULL;
    g_files[3].extents[0].file_end = 4000000000ULL;
    g_files[3].extents[0].lba_start = 65511624ULL;
    g_files[3].extents[0].lba_end = 73324127ULL;
    g_files[3].extents[0].num_clusters = 976563ULL;
    g_files[3].active = 1;
    g_files[3].http_sock = -1;
    pthread_mutex_init(&g_files[3].vf_mu, NULL);
    pthread_cond_init(&g_files[3].vf_cv, NULL);

    /* Entry 4: 05 - SBT RJ.ts (Inode 31, 4000000000 B) */
    memset(&g_files[4], 0, sizeof(struct virtual_file));
    g_files[4].file_id = 4;
    strncpy(g_files[4].id, "207198", sizeof(g_files[4].id) - 1);
    strncpy(g_files[4].name, "SBT RJ FHD¹", sizeof(g_files[4].name) - 1);
    strncpy(g_files[4].path, "05 - SBT RJ.ts", sizeof(g_files[4].path) - 1);
    g_files[4].file_size = 4000000000ULL;
    g_files[4].src_type = SRC_LIVE_FIFO;
    g_files[4].state = VOD_STATE_READY;
    g_files[4].bytes_available = 4000000000ULL;
    g_files[4].num_extents = 1;
    g_files[4].extents[0].id = 0;
    g_files[4].extents[0].vcn_start = 0ULL;
    g_files[4].extents[0].vcn_end = 976562ULL;
    g_files[4].extents[0].lcn_start = 9165516ULL;
    g_files[4].extents[0].lcn_end = 10142078ULL;
    g_files[4].extents[0].file_start = 0ULL;
    g_files[4].extents[0].file_end = 4000000000ULL;
    g_files[4].extents[0].lba_start = 73324128ULL;
    g_files[4].extents[0].lba_end = 81136631ULL;
    g_files[4].extents[0].num_clusters = 976563ULL;
    g_files[4].active = 1;
    g_files[4].http_sock = -1;
    pthread_mutex_init(&g_files[4].vf_mu, NULL);
    pthread_cond_init(&g_files[4].vf_cv, NULL);

    /* Entry 5: 06 - REDE TV.ts (Inode 32, 4000000000 B) */
    memset(&g_files[5], 0, sizeof(struct virtual_file));
    g_files[5].file_id = 5;
    strncpy(g_files[5].id, "208423", sizeof(g_files[5].id) - 1);
    strncpy(g_files[5].name, "REDE TV FHD¹", sizeof(g_files[5].name) - 1);
    strncpy(g_files[5].path, "06 - REDE TV.ts", sizeof(g_files[5].path) - 1);
    g_files[5].file_size = 4000000000ULL;
    g_files[5].src_type = SRC_LIVE_FIFO;
    g_files[5].state = VOD_STATE_READY;
    g_files[5].bytes_available = 4000000000ULL;
    g_files[5].num_extents = 2;
    g_files[5].extents[0].id = 0;
    g_files[5].extents[0].vcn_start = 0ULL;
    g_files[5].extents[0].vcn_end = 343679ULL;
    g_files[5].extents[0].lcn_start = 10142079ULL;
    g_files[5].extents[0].lcn_end = 10485758ULL;
    g_files[5].extents[0].file_start = 0ULL;
    g_files[5].extents[0].file_end = 1407713280ULL;
    g_files[5].extents[0].lba_start = 81136632ULL;
    g_files[5].extents[0].lba_end = 83886071ULL;
    g_files[5].extents[0].num_clusters = 343680ULL;
    g_files[5].extents[1].id = 1;
    g_files[5].extents[1].vcn_start = 343680ULL;
    g_files[5].extents[1].vcn_end = 976562ULL;
    g_files[5].extents[1].lcn_start = 1311144ULL;
    g_files[5].extents[1].lcn_end = 1944026ULL;
    g_files[5].extents[1].file_start = 1407713280ULL;
    g_files[5].extents[1].file_end = 4000000000ULL;
    g_files[5].extents[1].lba_start = 10489152ULL;
    g_files[5].extents[1].lba_end = 15552215ULL;
    g_files[5].extents[1].num_clusters = 632883ULL;
    g_files[5].active = 1;
    g_files[5].http_sock = -1;
    pthread_mutex_init(&g_files[5].vf_mu, NULL);
    pthread_cond_init(&g_files[5].vf_cv, NULL);

    /* Entry 6: 07 - RECORD TV RIO.ts (Inode 33, 4000000000 B) */
    memset(&g_files[6], 0, sizeof(struct virtual_file));
    g_files[6].file_id = 6;
    strncpy(g_files[6].id, "214640", sizeof(g_files[6].id) - 1);
    strncpy(g_files[6].name, "RECORD TV RIO FHD²", sizeof(g_files[6].name) - 1);
    strncpy(g_files[6].path, "07 - RECORD TV RIO.ts", sizeof(g_files[6].path) - 1);
    g_files[6].file_size = 4000000000ULL;
    g_files[6].src_type = SRC_LIVE_FIFO;
    g_files[6].state = VOD_STATE_READY;
    g_files[6].bytes_available = 4000000000ULL;
    g_files[6].num_extents = 1;
    g_files[6].extents[0].id = 0;
    g_files[6].extents[0].vcn_start = 0ULL;
    g_files[6].extents[0].vcn_end = 976562ULL;
    g_files[6].extents[0].lcn_start = 1944027ULL;
    g_files[6].extents[0].lcn_end = 2920589ULL;
    g_files[6].extents[0].file_start = 0ULL;
    g_files[6].extents[0].file_end = 4000000000ULL;
    g_files[6].extents[0].lba_start = 15552216ULL;
    g_files[6].extents[0].lba_end = 23364719ULL;
    g_files[6].extents[0].num_clusters = 976563ULL;
    g_files[6].active = 1;
    g_files[6].http_sock = -1;
    pthread_mutex_init(&g_files[6].vf_mu, NULL);
    pthread_cond_init(&g_files[6].vf_cv, NULL);

    /* Entry 7: 08 - SBT NEWS.ts (Inode 34, 4000000000 B) */
    memset(&g_files[7], 0, sizeof(struct virtual_file));
    g_files[7].file_id = 7;
    strncpy(g_files[7].id, "3030726", sizeof(g_files[7].id) - 1);
    strncpy(g_files[7].name, "SBT NEWS FHD¹", sizeof(g_files[7].name) - 1);
    strncpy(g_files[7].path, "08 - SBT NEWS.ts", sizeof(g_files[7].path) - 1);
    g_files[7].file_size = 4000000000ULL;
    g_files[7].src_type = SRC_LIVE_FIFO;
    g_files[7].state = VOD_STATE_READY;
    g_files[7].bytes_available = 4000000000ULL;
    g_files[7].num_extents = 1;
    g_files[7].extents[0].id = 0;
    g_files[7].extents[0].vcn_start = 0ULL;
    g_files[7].extents[0].vcn_end = 976562ULL;
    g_files[7].extents[0].lcn_start = 2920590ULL;
    g_files[7].extents[0].lcn_end = 3897152ULL;
    g_files[7].extents[0].file_start = 0ULL;
    g_files[7].extents[0].file_end = 4000000000ULL;
    g_files[7].extents[0].lba_start = 23364720ULL;
    g_files[7].extents[0].lba_end = 31177223ULL;
    g_files[7].extents[0].num_clusters = 976563ULL;
    g_files[7].active = 1;
    g_files[7].http_sock = -1;
    pthread_mutex_init(&g_files[7].vf_mu, NULL);
    pthread_cond_init(&g_files[7].vf_cv, NULL);

    /* Entry 8: 09 - TELECINE ACTION.ts (Inode 35, 4000000000 B) */
    memset(&g_files[8], 0, sizeof(struct virtual_file));
    g_files[8].file_id = 8;
    strncpy(g_files[8].id, "365244", sizeof(g_files[8].id) - 1);
    strncpy(g_files[8].name, "TELECINE ACTION FHD¹", sizeof(g_files[8].name) - 1);
    strncpy(g_files[8].path, "09 - TELECINE ACTION.ts", sizeof(g_files[8].path) - 1);
    g_files[8].file_size = 4000000000ULL;
    g_files[8].src_type = SRC_LIVE_FIFO;
    g_files[8].state = VOD_STATE_READY;
    g_files[8].bytes_available = 4000000000ULL;
    g_files[8].num_extents = 1;
    g_files[8].extents[0].id = 0;
    g_files[8].extents[0].vcn_start = 0ULL;
    g_files[8].extents[0].vcn_end = 976562ULL;
    g_files[8].extents[0].lcn_start = 3897153ULL;
    g_files[8].extents[0].lcn_end = 4873715ULL;
    g_files[8].extents[0].file_start = 0ULL;
    g_files[8].extents[0].file_end = 4000000000ULL;
    g_files[8].extents[0].lba_start = 31177224ULL;
    g_files[8].extents[0].lba_end = 38989727ULL;
    g_files[8].extents[0].num_clusters = 976563ULL;
    g_files[8].active = 1;
    g_files[8].http_sock = -1;
    pthread_mutex_init(&g_files[8].vf_mu, NULL);
    pthread_cond_init(&g_files[8].vf_cv, NULL);

    pthread_rwlock_unlock(&g_catalog_rwlock);
}

#endif /* CATALOG_FAVORITES_H */
